export const code =  {
    LC1: 
        {   lname: 'Two Sum',
            description: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.',
            algo: 'The simplest way is to use 2 for loops bot it will give you O(n^2). There is more elegant way to solve it with O(n) using Map (or object). The idea is that we enter for loop and check what number needed if we deduct the current number from target. The map contains previous numbers and their indices: NUMBER => INDEX. The simple check in the map - if number (key) is present, then value is the index of the second number in the result. First index is the current index of number in the for loop. Of course if number (key) is not present, then we add it to map.',
            solution:
            `var twoSum = function(nums, target) { 
            let hashMap = new Map();
            let result = []; //array of indices
            for (let i = 0; i < nums.length; i++) {
                let compensator = target - nums[i];
                if(hashMap.has(compensator)) {
                    result.push(i, hashMap.get(compensator));
                    return result;
                } else {
                    hashMap.set(nums[i], i);
                }
            }
            return -1;
            }`,
            speed: 65,
            memory: 43.7,
        },
    LC2: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC3: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC4: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC5: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC6: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC7: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC8: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC9: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC10: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC11: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC12: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC13: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC14: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC15: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC16: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC17: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC18: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC19: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC20: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC21: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC22: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC23: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC24: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC25: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC26: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC27: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC28: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC29: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC30: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC31: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC32: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC33: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC34: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC35: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC36: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC37: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC38: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC39: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC40: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC41: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC42: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC43: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC44: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC45: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC46: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC47: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC48: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC49: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC50: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
}