export const code =  {
    LC1: 
        {   lname: '1. Two Sum',
            description: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.',
            algo: 'The simplest way is to use 2 for loops bot it will give you O(n^2). There is more elegant way to solve it with O(n) using Map (or object). The idea is that we enter for loop and check what number needed if we deduct the current number from target. The map contains previous numbers and their indices: NUMBER => INDEX. The simple check in the map - if number (key) is present, then value is the index of the second number in the result. First index is the current index of number in the for loop. Of course if number (key) is not present, then we add it to map.',
            solution:
            `var twoSum = function(nums, target) { 
            let hashMap = new Map();
            let result = []; //array of indices
            for (let i = 0; i < nums.length; i++) {
                let compensator = target - nums[i];
                if(hashMap.has(compensator)) {
                    result.push(i, hashMap.get(compensator));
                    return result;
                } else {
                    hashMap.set(nums[i], i);
                }
            }
            return -1;
            }`,
            speed: 65,
            memory: 43.7,
        },
    LC2: {
        lname: '2. Add Two Numbers',
        description:'You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.<br> You may assume the two numbers do not contain any leading zero, except the number 0 itself.',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC3: {
        lname: '3. Longest Substring Without Repeating Characters',
        description:'Given a string s, find the length of the longest substring without repeating characters.',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC4: {
        lname: '4. Median of Two Sorted Arrays',
        description:'Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays. <br>The overall run time complexity should be O(log (m+n)).',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC5: {
        lname: '5. Longest Palindromic Substring',
        description:'Given a string s, return the longest palindromic substring in s.',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC6: {
        lname: '6. Zigzag Conversion',
        description:'The string "PAYPALISHIRING" is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility). And then read line by line: "PAHNAPLSIIGYIR". Write the code that will take a string and make this conversion given a number of rows: `string convert(string s, int numRows);`',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC7: {
        lname: '7. Reverse Integer',
        description:'Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range [-231, 231 - 1], then return 0. <br>Assume the environment does not allow you to store 64-bit integers (signed or unsigned).',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC8: {
        lname: '8. String to Integer (atoi)',
        description:'Implement the myAtoi(string s) function, which converts a string to a 32-bit signed integer (similar to C/C++\'s atoi function). <br>The algorithm for myAtoi(string s) is as follows:<br> Read in and ignore any leading whitespace. Check if the next character (if not already at the end of the string) is '-' or '+'. Read this character in if it is either. This determines if the final result is negative or positive respectively. Assume the result is positive if neither is present. Read in next the characters until the next non-digit character or the end of the input is reached. The rest of the string is ignored. <br>Convert these digits into an integer (i.e. "123" -> 123, "0032" -> 32). If no digits were read, then the integer is 0. Change the sign as necessary (from step 2). If the integer is out of the 32-bit signed integer range [-231, 231 - 1], then clamp the integer so that it remains in the range. Specifically, integers less than -231 should be clamped to -231, and integers greater than 231 - 1 should be clamped to 231 - 1. Return the integer as the final result. <br>Note:<br> Only the space character \' \' is considered a whitespace character. Do not ignore any characters other than the leading whitespace or the rest of the string after the digits.',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC9: {
        lname: '9. Palindrome Number',
        description:'Given an integer x, return true if x is a palindrome, and false otherwise.',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC10: {
        lname: '10. Regular Expression Matching',
        description:`Given an input string s and a pattern p, implement regular expression matching with support for '.' and '*' where:
        '.' Matches any single character.​​​​
        '*' Matches zero or more of the preceding element.
        The matching should cover the entire input string (not partial).`,
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC11: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC12: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC13: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC14: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC15: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC16: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC17: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC18: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC19: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC20: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC21: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC22: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC23: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC24: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC25: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC26: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC27: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC28: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC29: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC30: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC31: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC32: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC33: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC34: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC35: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC36: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC37: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC38: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC39: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC40: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC41: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC42: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC43: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC44: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC45: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC46: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC47: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC48: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC49: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
    LC50: {
        lname: '',
        description:'',
        algo: '',
        solution: ``,
        speed: 0,
        memory: 0,
    },
}